language: r
r: bioc-release
cache: 
  packages: true
  apt: true
bioc_check: true
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --no-build-vignettes
os:
  - linux
apt_packages:
  - libhdf5-dev

