name: dockerize

on:
  push:
    branches: 
      - master
      - devel

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push master
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tanevski/mistyr:master,tanevski/mistyr:latest
      -
        name: Build and push other
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tanevski/mistyr:${GITHUB_REF##*/}